name: Test

on:
  issues:
    types: [assigned]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test2
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"'
        
